### ISSUE TITLE
URI ISSUE

### ISSUE THREAD

**Issue by MokiMeow** [SkidGod4444/x0-GPT#2]
hey didnt want to take too much time but i am getting issue with the uri , my bad if i sound a noob but i am fairly new to supabase , i have created the google auth id and stored in the provider of the supabase but still when i login its registers in supabase but it doesn't redirect to the chat page it just in syncing i checked the network it said it had error in uri but i cant figure out how and why if u could guide me @
![Screenshot 2024-09-24 235812](https://github.com/user-attachments/assets/b542aefb-9580-4edb-8090-55f6e7be44bf)
![Screenshot 2024-09-24 235828](https://github.com/user-attachments/assets/14217a85-635b-4c12-91f6-491303bb887a)

![Screenshot 2024-09-24 235911](https://github.com/user-attachments/assets/3f854b53-d8d2-4e9f-80ba-7b5d97a6c77f)
hope u could help me with this minor issue

**Comment by SkidGod4444** [comment]
Try enabling realtime on your supabase table and if you still face issues.
Just schedule a meeting with me I will guide: https://devwtf.in
